package api

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/go-pdf/fpdf"

	"github.com/4yi-ai/codescan/internal/store"
)

// severity display order + colors for the PDF report.
type sevStyle struct {
	key     string
	label   string
	r, g, b int
}

var pdfSeverities = []sevStyle{
	{"critical", "CRITICAL", 220, 53, 69},
	{"high", "HIGH", 255, 140, 66},
	{"medium", "MEDIUM", 214, 170, 30},
	{"low", "LOW", 90, 170, 210},
	{"info", "INFO", 140, 140, 140},
}

// buildPDF renders a human-readable security report for a scan. It uses a
// pure-Go PDF library (no headless browser), so it works offline in the pod.
func buildPDF(job *store.Job, findings []store.Finding) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetTextColor(25, 28, 35)
	pdf.Cell(0, 10, "CodeScan Security Report")
	pdf.Ln(11)

	// Metadata
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(90, 96, 105)
	for _, m := range []string{
		"Source:  " + job.SourceRef,
		"Type:  " + job.SourceType + "        Status:  " + job.Status,
		"Scan ID:  " + job.ID,
	} {
		pdf.Cell(0, 5, pdfSafe(m))
		pdf.Ln(5)
	}
	pdf.Ln(3)

	// Summary badges
	sum := job.Summary
	if sum == nil {
		sum = &store.Summary{}
	}
	drawSummary(pdf, sum, len(findings))
	pdf.Ln(10)

	if len(findings) == 0 {
		pdf.SetFont("Helvetica", "", 11)
		pdf.SetTextColor(60, 120, 80)
		pdf.Cell(0, 8, "No findings. The scanned source is clean.")
		return output(pdf)
	}

	// Group findings by severity.
	groups := map[string][]store.Finding{}
	for _, f := range findings {
		k := strings.ToLower(f.Severity)
		groups[k] = append(groups[k], f)
	}

	for _, o := range pdfSeverities {
		fs := groups[o.key]
		if len(fs) == 0 {
			continue
		}
		// Section header
		pdf.SetFont("Helvetica", "B", 12)
		pdf.SetTextColor(o.r, o.g, o.b)
		pdf.Cell(0, 8, fmt.Sprintf("%s  (%d)", o.label, len(fs)))
		pdf.Ln(9)
		for i := range fs {
			renderFinding(pdf, &fs[i], o)
		}
		pdf.Ln(3)
	}

	// Footer note on the last page.
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(150, 150, 150)
	pdf.Ln(2)
	pdf.Cell(0, 5, "Generated by CodeScan - Semgrep (SAST) + Trivy (SCA/secret/IaC/license). No LLM, zero tokens.")

	return output(pdf)
}

func output(pdf *fpdf.Fpdf) ([]byte, error) {
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func drawSummary(pdf *fpdf.Fpdf, s *store.Summary, total int) {
	pdf.SetFont("Helvetica", "B", 10)
	items := []struct {
		label   string
		n       int
		r, g, b int
	}{
		{"Critical", s.Critical, 220, 53, 69},
		{"High", s.High, 255, 140, 66},
		{"Medium", s.Medium, 214, 170, 30},
		{"Low", s.Low, 90, 170, 210},
		{"Info", s.Info, 140, 140, 140},
	}
	for _, it := range items {
		pdf.SetFillColor(it.r, it.g, it.b)
		pdf.SetTextColor(255, 255, 255)
		txt := fmt.Sprintf(" %d %s ", it.n, it.label)
		w := pdf.GetStringWidth(txt) + 3
		pdf.CellFormat(w, 7, txt, "", 0, "C", true, 0, "")
		pdf.CellFormat(2, 7, "", "", 0, "L", false, 0, "")
	}
	pdf.SetTextColor(120, 120, 120)
	pdf.SetFont("Helvetica", "", 10)
	pdf.CellFormat(0, 7, fmt.Sprintf("  %d total", total), "", 0, "L", false, 0, "")
}

// depPill draws a small inline tag (used for DIRECT / transitive). It advances
// the cursor on the same line so the finding title can follow.
func depPill(pdf *fpdf.Fpdf, label string, r, g, b int, filled bool) {
	pdf.SetFont("Helvetica", "B", 6.5)
	txt := " " + label + " "
	w := pdf.GetStringWidth(txt) + 1.5
	if filled {
		pdf.SetFillColor(r, g, b)
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(w, 4.4, txt, "", 0, "C", true, 0, "")
	} else {
		pdf.SetTextColor(r, g, b)
		pdf.CellFormat(w, 4.4, txt, "", 0, "C", false, 0, "")
	}
	pdf.CellFormat(1.5, 4.4, "", "", 0, "L", false, 0, "")
}

func renderFinding(pdf *fpdf.Fpdf, f *store.Finding, o sevStyle) {
	// Colored left keyline for the severity.
	y := pdf.GetY()
	pdf.SetFillColor(o.r, o.g, o.b)
	pdf.Rect(15, y, 1.2, 4, "F")

	// Header: [DIRECT] badge + [category] rule / CVE. Direct dependencies (the
	// ones the user can fix themselves) get a bright, filled tag so they pop.
	rule := f.RuleID
	if rule == "" {
		rule = f.Title
	}
	pdf.SetX(18)
	switch f.Relationship {
	case "direct":
		depPill(pdf, "DIRECT", 56, 132, 255, true) // bright blue, filled
	case "indirect":
		depPill(pdf, "transitive", 150, 150, 150, false) // muted, low-key
	}
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(35, 38, 45)
	pdf.MultiCell(0, 5, pdfSafe(fmt.Sprintf("[%s] %s", f.Category, rule)), "", "L", false)

	// Location + package line
	loc := f.FilePath
	if f.Line > 0 {
		loc += fmt.Sprintf(":%d", f.Line)
	}
	if f.PkgName != "" {
		loc += "    " + f.PkgName
		if f.PkgVer != "" {
			loc += "@" + f.PkgVer
		}
		if f.FixedVer != "" {
			loc += "  ->  fix " + f.FixedVer
		}
	}
	if strings.TrimSpace(loc) != "" {
		pdf.SetX(18)
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(120, 125, 135)
		pdf.MultiCell(0, 4, pdfSafe(loc), "", "L", false)
	}

	// Detail message
	msg := f.Message
	if msg == "" {
		msg = f.Title
	}
	if strings.TrimSpace(msg) != "" && msg != rule {
		pdf.SetX(18)
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(70, 74, 82)
		pdf.MultiCell(0, 4, pdfSafe(msg), "", "L", false)
	}
	pdf.Ln(2.5)
}

// pdfSafe keeps printable ASCII (the core PDF fonts are Latin-1), replacing
// anything else with a space so exotic characters in CVE text can't corrupt the
// output.
func pdfSafe(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if r >= 32 && r < 127 {
			b.WriteRune(r)
		} else {
			b.WriteByte(' ')
		}
	}
	return strings.TrimSpace(b.String())
}
